on:
  push:
    branches:
    - master
    - release/*
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        
      - name: run
        run: |
          npm install
          npm run build --if-present
          
        
